[tool.poetry]
name = "arson"
version = "0.1.0"
description = ""
authors = ["arson <youaregifted@myyahoo.com>"]
readme = "README.md"
packages = [
    { include = "configs" }
]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^3.0.5"
numpy = "^2.5.2"
matplotlib = "^3.11.1"
seaborn = "^0.13.2"
jupyter = "^1.1.1"
sqlalchemy = "^2.0.52"
psycopg = "^3.3.4"
dotenv = "^0.9.9"
python-dotenv = "^1.2.3"
scipy = "^1.18.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
